export const PRODUCTS_SAVED = 'PRODUCTS_SAVED';
export const PRODUCTS_ALL = 'PRODUCTS_ALL';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const AJAX_END = 'AJAX_END';
export const PRODUCT_LOADED = 'PRODUCT_LOADED';
export const CHANGE_PRODUCT = 'CHANGE_PRODUCT';